stages:
  - docker
  - lint
  - cosine-test

workflow:
  auto_cancel:
    on_new_commit: conservative

# Include the steps for docker and playwright
include:
  # Build the Docker image
  - component: $CI_SERVER_FQDN/2pisoftware/pipelines/docker/build@v1.3.0
    inputs:
      stage: docker
      platforms: linux/amd64,linux/arm64

  - component: $CI_SERVER_FQDN/2pisoftware/pipelines/php/lint@2.2.1
    inputs:
      ignore: "*.js,*.css,system/lib/*"

  - component: $CI_SERVER_FQDN/2pisoftware/pipelines/php/test@2.2.1

php-lint:
  interruptible: true
  allow_failure: true
   
docker-build:
  interruptible: true
  tags:
    - largemem_x86

cosine-test:
  interruptible: true